services:
  - type: web
    name: st-application
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false   # set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false   # set this manually in Render dashboard
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
